name: Mindfulness FX
favicon: null
layout_spectrum: 0.5167264
typography_spectrum: 0.4199522
title: Mindfulness FX
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F2F1FA'
    - '#527801'
    - '#162701'
    - '#0055A0'
    - '#CF926E'
  brandStrength: 0.5
  lightness: 0.4375
  saturation: 0.875
  rhythmicContrast: 0.25
purpose: []
