name: Mindfulness FX
favicon: null
layout_spectrum: 0.29265065328218043
typography_spectrum: 0.8329064208082855
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6815835083834827
  lightness: 0.7360693349037319
  saturation: 0.3738616982009262
  rhythmicContrast: 0.6684568270575255
purpose: []
